# Generated by Django 5.0.6 on 2024-06-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_userbookrelation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrelation',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
